import "./globals.css";
import Providers from "@utils/provider";
import font from "@utils/fonts";
import { ThemeProvider } from "../context/ThemeContext";

export const metadata = {
  title: "FarmExpo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.raleway.className} bg-LightPBg dark:bg-DarkPBg text-LightPText dark:text-DarkPText`}
      >
        <ThemeProvider>
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
